project_id = "ackbxokwnkagolepezmp"

[functions.grant-achievements]
verify_jwt = false

[functions.send-prayer-reminders]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.get-vapid-key]
verify_jwt = false

[functions.ai-assistant]
verify_jwt = false
 
 [functions.generate-daily-devotional]
 verify_jwt = false
 
 [functions.generate-auto-quiz]
 verify_jwt = false
